apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    debug = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          minVersion = "VersionTLS12"
          cipherSuites = [ "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA" ]
    [file]
      watch = true    
    [kubernetes]
    [web]
    address=":8081"
    [acme]
    email = "valid@email.ltd"
    storage = "acme.json"
    entryPoint = "https"
    acmeLogging = true
    onHostRule = true
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    # caServer = "https://acme-v02.api.letsencrypt.org/directory"
      [acme.httpChallenge]
      entryPoint="http"
    [[acme.domains]]
      main = "youhost.k8s.yourdomain.nl"

