apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        value: "true"
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.2-debian-kafka
        env:
          - name:  FLUENT_KAFKA_BROKERS 
            value: "my-kafka.default.svc.cluster.local:9092"
          - name:  FLUENT_KAFKA_DEFAULT_TOPIC 
            value: "k8slogs"
          - name: FLUENT_KAFKA_COMPRESSION_CODEC
            value: "gzip"
          - name: FLUENT_KAFKA_MAX_SEND_LIMIT_BYTES
            value: "1000000"
          - name: FLUENT_KAFKA_DEFAULT_PARTITION_KEY
            value: "3"
          - name: FLUENT_KAFKA_GET_KAFKA_CLIENT_LOG
            value: "true"
          - name: FLUENT_KAFKA_ACK_TIMEOUT
            value: "1"
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 300Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

