apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "thisis@mymail.ltd"
  # configure letsencrypt's production api
  lego.url: "https://acme-staging.api.letsencrypt.org/directory"
kind: ConfigMap
