kind: ConfigMap
apiVersion: v1
metadata:
  name: locustfile
  namespace: loadtesting
data:
  locustfile.py: |-
    from locust import HttpUser, task, between

    class MyUser(HttpUser):
      wait_time = between(5, 15)

      @task(4)
      def index(self):
        self.client.get("/")

      @task(1)
      def about(self):
        self.client.get("/about/")
