apiVersion: v1
kind: Service
metadata:
  name: locustmaster
  namespace: loadtesting
  labels:
    app: locustmaster
    tool: locust
spec:
  ports:
    - name: ui
      port: 8089
      protocol: TCP
      targetPort: 8089
    - name: masterp1
      port: 5557
      protocol: TCP
      targetPort: 5557
    - name: masterp2
      port: 5558
      protocol: TCP
      targetPort: 5558
  selector:
    app: locustmaster
    tier: loadtesting
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: locustmaster-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  namespace: loadtesting
  labels:
    tool: locust
spec:
  ingressClassName: nginx
  rules:
    - host: locust.k8s.yourdomain.ltd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: locustmaster
                port: 
                  number: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locustmaster
  namespace: loadtesting
  labels:
    app: locustmaster
    tool: locust
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: locustmaster
      tier: loadtesting
  template:
    metadata:
      labels:
        app: locustmaster
        tier: loadtesting
    spec:
      containers:
      - image: pblaas/locust-alpine:dev
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
        name: locustmaster
        volumeMounts:
          - name: locustfile-config
            mountPath: /test
        env:
        - name: LOCUST_MODE
          value: master
        - name: TARGET_URL
          value: http://yourtargeturl.ltd
        - name: SCENARIO_FILE
          value: /test/locustfile.py
        ports:
        - containerPort: 8089
          name: locustmaster
      volumes:
        - name: locustfile-config
          configMap:
            name: locustfile
