apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: jenkins
  name: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: jenkins
 namespace: jenkins
spec:
 rules:
   - host: jenkins.k8s.yourdomain.ltd
     http:
       paths:
         - path: /
           backend:
             serviceName: jenkins
             servicePort: 8080
---
apiVersion: v1
data:
  jenkins-admin-password: RldNYm1YZWJ3TjNuUFFs
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
type: Opaque
---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins
  namespace: jenkins
spec: 
  type: NodePort
  selector: 
    app: master
  ports: 
    - 
      name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - 
      name: slave
      port: 50000
      protocol: TCP        

---

