#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

apiVersion: v1
kind: Service
metadata:
  name: alluxio-master
  labels:
    app: alluxio
spec:
  ports:
  - port: 19998
    name: rpc
  - port: 19999
    name: web
  clusterIP: None
  selector:
    app: alluxio-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alluxio-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: alluxio-master
spec:
  selector:
    matchLabels:
      app: alluxio-master
  serviceName: "alluxio-master"
  replicas: 1
  template:
    metadata:
      labels:
        app: alluxio-master
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      #Required for Nagoya non resolvable hostnames
      #hostAliases:
      #- ip: "192.168.3.10"                         
      #  hostnames:                                 
      #  - "k8s-k8scluster-node10"                  
      #- ip: "192.168.3.11"                         
      #  hostnames:                                 
      #  - "k8s-k8scluster-node11"                  
      #- ip: "192.168.3.12"                         
      #  hostnames:                                 
      #  - "k8s-k8scluster-node12"                  
      #- ip: "192.168.3.13"                         
      #  hostnames:                                 
      #  - "k8s-k8scluster-node13"                  
      #- ip: "192.168.3.14"                         
      #  hostnames:                                 
      #  - "k8s-k8scluster-node14"                  
      #- ip: "192.168.3.15"                         
      #  hostnames:                                 
      #  - "k8s-k8scluster-node15"
      containers:
        - name: alluxio-master
          image: pblaas/alluxio:1.8.1
          resources:
            requests:
              cpu: "0.5"
              memory: "512M"
            limits:
              cpu: "1"
              memory: "1024M"
          command: ["/entrypoint.sh"]
          args: ["master"]
          envFrom:
          - configMapRef:
              name: alluxio-config
          ports:
          - containerPort: 19998
            name: rpc
          - containerPort: 19999
            name: web
          volumeMounts:
            - name: alluxio-journal
              mountPath: /journal
            - name: alluxio-domain
              mountPath: /opt/domain
      restartPolicy: Always
      volumes:
        - name: alluxio-journal
          persistentVolumeClaim:
            claimName: alluxio-pv-claim
        - name: alluxio-domain
          emptyDir:
            medium: "Memory"
            sizeLimit: "1G"

